version: '3.9'
services:
  redis:
    image: redis
    restart: unless-stopped
    container_name: redis-cache
  postgres:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    container_name: backend-app
    environment:
      - REDIS_HOST=redis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
  frontend:
    build: 
      context: ./example-frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: frontend-app
