version: '3.9'
services:
  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: backend-app
  frontend:
    build: 
      context: ./example-frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: frontend-app
